In [1]:
import numpy as np
import pandas as pd

In [2]:
# data = pd.read_stata(r"Z:\harmonized\ECU\ENEMDU\data_arm\ECU_1990m11_BID.dta") # para bases de stata
data = pd.read_stata(r"Bases Enendum 96, 97, 98\ECU_1996m11.dta") # para bases de stata

In [3]:
data['sexo']

0         mujer
1        hombre
2         mujer
3        hombre
4        hombre
          ...
37259    hombre
37260    hombre
37261     mujer
37262     mujer
37263     mujer
Name: sexo, Length: 37264, dtype: category
Categories (2, object): ['hombre' < 'mujer']

In [4]:
data['sexo'][0]

'mujer'

In [5]:
len(data) # te da el valor total de la variable data

37264

In [6]:
len(data.loc[data['sexo'] == 'mujer']) # te da el valor total de la variable sexo-mujer

19070

In [7]:
len(data.loc[data['sexo'] == 'mujer']) / len(data) # len sirve para contar la cantidad de info de una variable, en este caso sexo-mujer y luego se dividio para el total de la info para medir el porcentaje

0.5117539716616574

In [8]:
data #muestra el archivo o matriz en este caso del stata, tipo excel

,dominio,rn,ciudad,zona,sector,vivienda,hogar,formul,persona,numpers,...,sep,oct,condact,peamsiu,secins,subequ,ingrl,fexp1,fexp2,fexp
0,3,1,010150,023,007,03,1,1,1,1,...,sin buscar trabajo,sin buscar trabajo,inactivos,NaN,0,0,0,75,87,87
1,3,1,010150,023,007,04,1,1,1,5,...,trabajando,trabajando,informales,informal,1,0,0,75,87,87
2,3,1,010150,023,007,04,1,1,2,5,...,sin buscar trabajo,sin buscar trabajo,inactivos,NaN,0,0,0,75,87,87
3,3,1,010150,023,007,04,1,1,3,5,...,trabajando,trabajando,ocupados no bién definidos,moderno,2,0,0,75,87,87
4,3,1,010150,023,007,04,1,1,4,5,...,trabajando,trabajando,ocupados plenos,moderno,1,0,0,75,87,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37259,1,1,170150,152,005,10,1,1,4,4,...,sin buscar trabajo,sin buscar trabajo,inactivos,NaN,0,0,0,325,379,384
37260,1,1,170150,152,005,11,1,1,1,3,...,trabajando,trabajando,informales,informal,1,0,0,325,379,384
37261,1,1,170150,152,005,11,1,1,2,3,...,trabajando,trabajando,informales,informal,1,0,0,325,379,384
37262,1,1,170150,152,005,11,1,1,3,3,...,NaN,NaN,menores de 10 años,NaN,0,0,0,325,379,384
37263,1,1,170150,152,005,12,1,1,1,1,...,trabajando,trabajando,informales,informal,1,0,0,325,379,384

In [9]:
data.loc[data['sexo'] == 'mujer'] # muestra solo la info mujer de la variable sexo

,dominio,rn,ciudad,zona,sector,vivienda,hogar,formul,persona,numpers,...,sep,oct,condact,peamsiu,secins,subequ,ingrl,fexp1,fexp2,fexp
0,3,1,010150,023,007,03,1,1,1,1,...,sin buscar trabajo,sin buscar trabajo,inactivos,NaN,0,0,0,75,87,87
2,3,1,010150,023,007,04,1,1,2,5,...,sin buscar trabajo,sin buscar trabajo,inactivos,NaN,0,0,0,75,87,87
5,3,1,010150,023,007,04,1,1,5,5,...,sin buscar trabajo,sin buscar trabajo,inactivos,NaN,0,0,0,75,87,87
7,3,1,010150,023,007,06,1,1,2,5,...,trabajando,trabajando,ocupados plenos,moderno,2,0,700000,75,87,87
12,3,1,010150,023,007,07,1,1,2,5,...,sin buscar trabajo,sin buscar trabajo,inactivos,NaN,0,0,0,75,87,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37254,1,1,170150,152,005,09,1,1,4,5,...,NaN,NaN,menores de 10 años,NaN,0,0,0,325,379,384
37257,1,1,170150,152,005,10,1,1,2,4,...,sin buscar trabajo,sin buscar trabajo,inactivos,NaN,0,0,0,325,379,384
37261,1,1,170150,152,005,11,1,1,2,3,...,trabajando,trabajando,informales,informal,1,0,0,325,379,384
37262,1,1,170150,152,005,11,1,1,3,3,...,NaN,NaN,menores de 10 años,NaN,0,0,0,325,379,384
37263,1,1,170150,152,005,12,1,1,1,1,...,trabajando,trabajando,informales,informal,1,0,0,325,379,384

In [10]:
data.columns # muestra el nombre de cada variable

Index(['dominio', 'rn', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar',
       'formul', 'persona', 'numpers', 'resumen', 'reljefe', 'edad', 'sexo',
       'nivinst', 'anoinst', 'asistea', 'sabele', 'iess', 'donnac', 'lugnac',
       'siemvic', 'donvian', 'lugvian', 'cuanvic', 'trabajo', 'actayuda',
       'hortrasa', 'ratmeh', 'hormas', 'ratmah', 'aunotra', 'pornot',
       'bustrasa', 'bustrama', 'sitios', 'amigos', 'directo', 'prensa',
       'agepu', 'agepri', 'tresne', 'tiembus', 'motnobus', 'deseatra',
       'condina', 'trabant', 'motnotra', 'tiemnot', 'rama', 'grupo',
       'catetrab', 'pertrabn', 'npertra', 'numtrab', 'estabil', 'hortrahp',
       'hortrahs', 'hortraho', 'ramas', 'grupos', 'cates', 'ingpat', 'ingasg',
       'ingepv', 'ingdom', 'ingjub', 'ingalq', 'ingotr', 'nov', 'dic', 'ene',
       'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct',
       'condact', 'peamsiu', 'secins', 'subequ', 'ingrl', 'fexp1', 'fexp2',
       'fexp'],
      dtype='object')

- rn - región natural
- dominio - dominio
- cuidad - ciudad
- zona - zona
- sector - sector
- vivienda - vivienda
- hogar - hogar
- formul - formulario
- persona - persona
- numpers - número de personas
- resumen - resultado entrevista
- reljefe - relacion de parentesco 
- edad - edad
- sexo - sexo 
- iess - es afiliado al iess
- trabajo - trabajo la semana pasada
- catetrab - categoría de ocupación
- rama - rama de actividad
- grupo - grupo de ocupación
- ramas - rama de actividad secundaria
- grupos - grupo de ocupación secundario
- cates - categoría de ocupación secundaria
- ingpat - ingresos como patrono o cuenta propia
- ingasg - ingresos como asalariado de gobierno
- ingepv - ingreso asalariado empresa privada
- ingdom - ingreso como empleada doméstica
- ingjub - ingresos por jubilación o pensión
- ingotr - por otros ingresos
- ingrl - ingresos
- fexp1 - factor de expansión 1
- fexp2 - factor de expansión 2
- fexp - factor de expansión 

El valor de 'salbasic' es el ingreso laboral monetario, no hay datos sobre ingreso laboral no monetario hay relación entre 'salbasic' y 'rulpago' y 'formapago'.
![image.png](attachment:image.png) 

Hay variables dicotomicas para cada mes (ene, feb, mar, abr, may, jun, jul, ago, sep, oct, nov, dic) que dicen si estuvo o no ocupado, se puede usar estas variables y el salario básico asumiendo que cuando estaba ocupado tenía ese salario para intentar aproximar el salario mensual y de ahí el salario trimestral, esto solo funciona así ya que no tenemos una variable que explicite el mes, en encuestas que tengan el mes o trimestre explícito esto no sería igual.

In [11]:
data['nov']

0        sin buscar trabajo
1                trabajando
2        sin buscar trabajo
3                trabajando
4                trabajando
                ...
37259    sin buscar trabajo
37260            trabajando
37261            trabajando
37262                   NaN
37263            trabajando
Name: nov, Length: 37264, dtype: category
Categories (3, object): ['trabajando' < 'buscando trabajo' < 'sin buscar trabajo']

In [12]:
data = data[['dominio', 'rn', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar',
       'formul', 'persona', 'numpers', 'resumen', 'edad', 'sexo', 'iess', 'trabajo', 'catetrab', 'ingpat', 'ingasg', 'ingepv', 'ingdom', 'ingjub', 'ingrl', 'fexp1', 'fexp2', 'fexp', 'ene',
       'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic',]]

In [13]:
data ['sum_ing'] = data [['ingasg', 'ingepv', 'ingdom']].sum(axis=1)

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2018387626.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data ['sum_ing'] = data [['ingasg', 'ingepv', 'ingdom']].sum(axis=1)

In [14]:
data['suma_ing_ene'] = data.apply(lambda x: x['sum_ing'] if x['ene'] == 'trabajando' else None, axis=1)
data['suma_ing_feb'] = data.apply(lambda x: x['sum_ing'] if x['feb'] == 'trabajando' else None, axis=1)
data['suma_ing_mar'] = data.apply(lambda x: x['sum_ing'] if x['mar'] == 'trabajando' else None, axis=1)
data['suma_ing_abr'] = data.apply(lambda x: x['sum_ing'] if x['abr'] == 'trabajando' else None, axis=1)
data['suma_ing_may'] = data.apply(lambda x: x['sum_ing'] if x['may'] == 'trabajando' else None, axis=1)
data['suma_ing_jun'] = data.apply(lambda x: x['sum_ing'] if x['jun'] == 'trabajando' else None, axis=1)
data['suma_ing_jul'] = data.apply(lambda x: x['sum_ing'] if x['jul'] == 'trabajando' else None, axis=1)
data['suma_ing_ago'] = data.apply(lambda x: x['sum_ing'] if x['ago'] == 'trabajando' else None, axis=1)
data['suma_ing_sep'] = data.apply(lambda x: x['sum_ing'] if x['sep'] == 'trabajando' else None, axis=1)
data['suma_ing_oct'] = data.apply(lambda x: x['sum_ing'] if x['oct'] == 'trabajando' else None, axis=1)
data['suma_ing_nov'] = data.apply(lambda x: x['sum_ing'] if x['nov'] == 'trabajando' else None, axis=1)
data['suma_ing_dic'] = data.apply(lambda x: x['sum_ing'] if x['dic'] == 'trabajando' else None, axis=1)

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_ene'] = data.apply(lambda x: x['sum_ing'] if x['ene'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_feb'] = data.apply(lambda x: x['sum_ing'] if x['feb'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_mar'] = data.apply(lambda x: x['sum_ing'] if x['mar'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_abr'] = data.apply(lambda x: x['sum_ing'] if x['abr'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_may'] = data.apply(lambda x: x['sum_ing'] if x['may'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_jun'] = data.apply(lambda x: x['sum_ing'] if x['jun'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_jul'] = data.apply(lambda x: x['sum_ing'] if x['jul'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_ago'] = data.apply(lambda x: x['sum_ing'] if x['ago'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_sep'] = data.apply(lambda x: x['sum_ing'] if x['sep'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_oct'] = data.apply(lambda x: x['sum_ing'] if x['oct'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_nov'] = data.apply(lambda x: x['sum_ing'] if x['nov'] == 'trabajando' else None, axis=1)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\3304403396.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_dic'] = data.apply(lambda x: x['sum_ing'] if x['dic'] == 'trabajando' else None, axis=1)

In [15]:
data['suma_ing_t1'] = (data['suma_ing_ene'] + data['suma_ing_feb'] + data['suma_ing_mar'])/3
data['suma_ing_t2'] = (data['suma_ing_abr'] + data['suma_ing_may'] + data['suma_ing_jun'])/3
data['suma_ing_t3'] = (data['suma_ing_jul'] + data['suma_ing_ago'] + data['suma_ing_sep'])/3
data['suma_ing_t4'] = (data['suma_ing_oct'] + data['suma_ing_nov'] + data['suma_ing_dic'])/3

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2041548675.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_t1'] = (data['suma_ing_ene'] + data['suma_ing_feb'] + data['suma_ing_mar'])/3
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2041548675.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_t2'] = (data['suma_ing_abr'] + data['suma_ing_may'] + data['suma_ing_jun'])/3
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2041548675.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_t3'] = (data['suma_ing_jul'] + data['suma_ing_ago'] + data['suma_ing_sep'])/3
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2041548675.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_t4'] = (data['suma_ing_oct'] + data['suma_ing_nov'] + data['suma_ing_dic'])/3

In [16]:
# Llenar valores perdidos con un dato (0)
data['suma_ing_t1'] = data['suma_ing_t1'].fillna(0)
data['suma_ing_t2'] = data['suma_ing_t2'].fillna(0)
data['suma_ing_t3'] = data['suma_ing_t3'].fillna(0)
data['suma_ing_t4'] = data['suma_ing_t4'].fillna(0)

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\1840857865.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_t1'] = data['suma_ing_t1'].fillna(0)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\1840857865.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_t2'] = data['suma_ing_t2'].fillna(0)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\1840857865.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_t3'] = data['suma_ing_t3'].fillna(0)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\1840857865.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['suma_ing_t4'] = data['suma_ing_t4'].fillna(0)

In [17]:
data

,dominio,rn,ciudad,zona,sector,vivienda,hogar,formul,persona,numpers,...,suma_ing_jul,suma_ing_ago,suma_ing_sep,suma_ing_oct,suma_ing_nov,suma_ing_dic,suma_ing_t1,suma_ing_t2,suma_ing_t3,suma_ing_t4
0,3,1,010150,023,007,03,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,3,1,010150,023,007,04,1,1,1,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,1,010150,023,007,04,1,1,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,3,1,010150,023,007,04,1,1,3,5,...,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0
4,3,1,010150,023,007,04,1,1,4,5,...,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37259,1,1,170150,152,005,10,1,1,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
37260,1,1,170150,152,005,11,1,1,1,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37261,1,1,170150,152,005,11,1,1,2,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37262,1,1,170150,152,005,11,1,1,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
37263,1,1,170150,152,005,12,1,1,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [2]:
# data = pd.read_stata(r"Z:\harmonized\ECU\ENEMDU\data_arm\ECU_1990m11_BID.dta") # para bases de stata
data = pd.read_stata(r"datos/ECU_1996m11_BID.dta") # para bases de stata

data['suma_ing_t1'].mean()

In [19]:
pip install openpyxl

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: openpyxl in c:\users\jairo\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\jairo\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import openpyxl
print(openpyxl.__version__)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37264 entries, 0 to 37263
Columns: 252 entries, region_BID_c to ppp_wdi2011
dtypes: category(77), float32(18), float64(105), int16(8), int32(1), int8(33), object(10)
memory usage: 39.9+ MB

In [21]:
import pandas as pd

data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos', engine='openpyxl')

In [4]:
datos_actual

Index(['region_BID_c', 'region_c', 'pais_c', 'anio_c', 'mes_c', 'zona_c',
       'factor_ch', 'idh_ch', 'idp_ci', 'factor_ci',
       ...
       'formal', 'formal_1', 'ylm_ci1', 'ynlm_ci1', 'aguafconsumo_ch',
       'aguafuente_ch', 'aguadisp1_ch', 'aguadisp2_ch', 'sinbano_ch',
       'ppp_wdi2011'],
      dtype='object', length=252)

In [5]:
ipc_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Guayaquil': fila['Guayaquil'],
        'Quito': fila['Quito'],
        'Cuenca': fila['Cuenca']
    }
     for _, fila in datos_actual.iterrows()
     }

ipc_base_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Guayaquil': fila['Guayaquil'],
        'Quito': fila['Quito'],
        'Cuenca': fila['Cuenca']
    }
     for _, fila in datos_base.iterrows()
     }

tipo_cambio_dict = dict(zip(datos_actual['trimestre'], datos_actual['tipo de cambio']))

In [6]:
tipo_cambio_dict

{1: 2998.33333333333, 2: 3130.0, 3: 3268.0, 4: 3493.0}

In [7]:
ipc_dict

{np.float64(1.0): {'Nacional': np.float64(7.32721327856884),
  'Guayaquil': np.float64(8.31254040971796),
  'Quito': np.float64(7.70346904009364),
  'Cuenca': np.float64(6.14523115234842)},
 np.float64(2.0): {'Nacional': np.float64(7.32721327856884),
  'Guayaquil': np.float64(8.31254040971796),
  'Quito': np.float64(7.70346904009364),
  'Cuenca': np.float64(6.14523115234842)},
 np.float64(3.0): {'Nacional': np.float64(7.32721327856884),
  'Guayaquil': np.float64(8.31254040971796),
  'Quito': np.float64(7.70346904009364),
  'Cuenca': np.float64(6.14523115234842)},
 np.float64(4.0): {'Nacional': np.float64(7.32721327856884),
  'Guayaquil': np.float64(8.31254040971796),
  'Quito': np.float64(7.70346904009364),
  'Cuenca': np.float64(6.14523115234842)}}

In [27]:
ipc_base_dict

{np.float64(1.0): {'Nacional': np.float64(98.0830338739655),
  'Guayaquil': np.float64(98.1564632091738),
  'Quito': np.float64(97.8854386246834),
  'Cuenca': np.float64(97.8620864214017)},
 np.float64(2.0): {'Nacional': np.float64(98.8716926422298),
  'Guayaquil': np.float64(99.1715283859644),
  'Quito': np.float64(98.5213081168195),
  'Cuenca': np.float64(98.6441250354991)},
 np.float64(3.0): {'Nacional': np.float64(99.6677015365054),
  'Guayaquil': np.float64(100.172597125045),
  'Quito': np.float64(99.7166913492557),
  'Cuenca': np.float64(99.4057692585417)},
 np.float64(4.0): {'Nacional': np.float64(100.50639978567),
  'Guayaquil': np.float64(100.653894938944),
  'Quito': np.float64(100.539782511322),
  'Cuenca': np.float64(100.232265443248)}}

In [8]:
# Corregimos los códigos para usarlos cómo texto
data['ciudad'] = data['ciudad'].apply(str)
data['ciudad'] = data['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)

data['ciudad_2'] = data['ciudad'].apply(lambda x: x[:2])

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2908473067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ciudad'] = data['ciudad'].apply(str)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2908473067.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ciudad'] = data['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2908473067.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ciudad_2'] = data['ciudad'].apply(lambda x: x[:2])

In [29]:
data['ciudad']

0        010150
1        010150
2        010150
3        010150
4        010150
          ...
37259    170150
37260    170150
37261    170150
37262    170150
37263    170150
Name: ciudad, Length: 37264, dtype: object

In [30]:
Esto deja todo en dólares constantes de 2014, utilizamos el IPC de Estados Unidos para ajustar por inflación ya que no podemos usar la inflación en sucres si queremos dejar el valor final en dólares de 2014

0        01
1        01
2        01
3        01
4        01
         ..
37259    17
37260    17
37261    17
37262    17
37263    17
Name: ciudad_2, Length: 37264, dtype: object

In [9]:
parroquia_dict = {
    '01': 'Cuenca',
    '09': 'Guayaquil',
    '17': 'Quito'
}

data['ciudad_asignada'] = data['ciudad_2'].apply(lambda x: parroquia_dict.get(x, 'Nacional'))

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\218289303.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ciudad_asignada'] = data['ciudad_2'].apply(lambda x: parroquia_dict.get(x, 'Nacional'))

In [32]:
data['ciudad_asignada']

0        Cuenca
1        Cuenca
2        Cuenca
3        Cuenca
4        Cuenca
          ...
37259     Quito
37260     Quito
37261     Quito
37262     Quito
37263     Quito
Name: ciudad_asignada, Length: 37264, dtype: object

In [10]:
ipc_dict = dict(zip(datos_actual['trimestre'], datos_actual['IPC Estados Unidos']))

ipc_base_dict = dict(zip(datos_base['trimestre'], datos_base['IPC Estados Unidos']))

tipo_cambio_dict = dict(zip(datos_actual['trimestre'], datos_actual['tipo de cambio']))

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2631173444.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['trimestre'] = data.apply(assgna_trimestre, axis=1)

In [34]:
### Asignamos el ipc y tipo de cambio correspondiente según trimestre

0        NaN
1        1.0
2        NaN
3        1.0
4        1.0
        ...
37259    NaN
37260    1.0
37261    1.0
37262    NaN
37263    1.0
Name: trimestre, Length: 37264, dtype: float64

In [38]:
$\begin{equation}
    ingr_{USD-base-2014}^{i} = \frac{ingr_{sucres}^{i}}{tipo-de-cambio^{i}}\left( \frac{ipcUSA^{i}_{2014}}{ipcUSA^{i}_{año}}\right)
\end{equation}$

Con $i$ el trimestre de interés y $año$ el año de interés

0              NaN
1        97.862086
2              NaN
3        97.862086
4        97.862086
           ...
37259          NaN
37260    97.885439
37261    97.885439
37262          NaN
37263    97.885439
Name: ipc_base, Length: 37264, dtype: float64

In [11]:
data['ipc_t1'] = ipc_dict.get(1)
data['ipc_base_t1'] = ipc_base_dict.get(1)
data['tipo_cambio_t1'] = tipo_cambio_dict.get(1)

data['ipc_t2'] = ipc_dict.get(2)
data['ipc_base_t2'] = ipc_base_dict.get(2)
data['tipo_cambio_t2'] = tipo_cambio_dict.get(2)

data['ipc_t3'] = ipc_dict.get(3)
data['ipc_base_t3'] = ipc_base_dict.get(3)
data['tipo_cambio_t3'] = tipo_cambio_dict.get(3)

data['ipc_t4'] = ipc_dict.get(4)
data['ipc_base_t4'] = ipc_base_dict.get(4)
data['tipo_cambio_t4'] = tipo_cambio_dict.get(4)

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\587192262.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['def'] = (data['ipc_base'] / data['ipc'])

In [12]:
data['def']

0              NaN
1        15.924883
2              NaN
3        15.924883
4        15.924883
           ...
37259          NaN
37260    12.706670
37261    12.706670
37262          NaN
37263    12.706670
Name: def, Length: 37264, dtype: float64

In [13]:
data['ingr_t1_r'] = (data['suma_ing_t1'] / data['tipo_cambio']) * data['def']
data['ingr_t2_r'] = (data['suma_ing_t2'] / data['tipo_cambio']) * data['def']
data['ingr_t3_r'] = (data['suma_ing_t3'] / data['tipo_cambio']) * data['def']
data['ingr_t4_r'] = (data['suma_ing_t4'] / data['tipo_cambio']) * data['def']

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\989630616.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ingr_t1_r'] = (data['suma_ing_t1'] / data['tipo_cambio']) * data['def']
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\989630616.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ingr_t2_r'] = (data['suma_ing_t2'] / data['tipo_cambio']) * data['def']
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\989630616.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ingr_t3_r'] = (data['suma_ing_t3'] / data['tipo_cambio']) * data['def']
C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\989630616.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ingr_t4_r'] = (data['suma_ing_t4'] / data['tipo_cambio']) * data['def']

In [43]:
data[['suma_ing_t1', 'suma_ing_t2', 'suma_ing_t3', 'suma_ing_t4', 'ipc', 'ipc_base', 'def', 'tipo_cambio', 'ingr_t1_r', 'ingr_t2_r', 'ingr_t3_r', 'ingr_t4_r']]

,suma_ing_t1,suma_ing_t2,suma_ing_t3,suma_ing_t4,ipc,ipc_base,def,tipo_cambio,ingr_t1_r,ingr_t2_r,ingr_t3_r,ingr_t4_r
0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,6.145231,97.862086,15.924883,2998.333333,0.000000,0.000000,0.000000,0.000000
2,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9999999.0,9999999.0,9999999.0,9999999.0,6.145231,97.862086,15.924883,2998.333333,53112.444566,53112.444566,53112.444566,53112.444566
4,9999999.0,9999999.0,9999999.0,9999999.0,6.145231,97.862086,15.924883,2998.333333,53112.444566,53112.444566,53112.444566,53112.444566
...,...,...,...,...,...,...,...,...,...,...,...,...
37259,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37260,0.0,0.0,0.0,0.0,7.703469,97.885439,12.706670,2998.333333,0.000000,0.000000,0.000000,0.000000
37261,0.0,0.0,0.0,0.0,7.703469,97.885439,12.706670,2998.333333,0.000000,0.000000,0.000000,0.000000
37262,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37263,0.0,0.0,0.0,0.0,7.703469,97.885439,12.706670,2998.333333,0.000000,0.000000,0.000000,0.000000

In [14]:
data['ingr_t1_r'] = (data['ingr_ene_r'] + data['ingr_feb_r'] + data['ingr_mar_r'])/3
data['ingr_t2_r'] = (data['ingr_abr_r'] + data['ingr_may_r'] + data['ingr_jun_r'])/3
data['ingr_t3_r'] = (data['ingr_jul_r'] + data['ingr_ago_r'] + data['ingr_sep_r'])/3
data['ingr_t4_r'] = (data['ingr_oct_r'] + data['ingr_nov_r'] + data['ingr_dic_r'])/3

data['ingr_t4_r'].mean()

In [15]:
columnas_idef = ['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar']

data['idef_hogar'] = data[columnas_idef].astype(str).agg(''.join, axis=1)
len(data['idef_hogar'].unique())

C:\Users\jairo\AppData\Local\Temp\ipykernel_10876\2378113009.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['idef_hogar'] = data[columnas_idef].astype(str).agg(''.join, axis=1)

8155

In [16]:
data[['ingr_t1_h', 'ingr_t2_h', 'ingr_t3_h', 'ingr_t4_h']]

,rn,dominio,ciudad,zona,sector,vivienda,hogar,idef_hogar,persona,numpers
0,1,3,10150,001,005,01,1,1310150001005011,3,3
1,1,3,10150,001,005,01,1,1310150001005011,1,3
2,1,3,10150,001,005,01,1,1310150001005011,2,3
3,1,3,10150,001,005,02,1,1310150001005021,4,4
4,1,3,10150,001,005,02,1,1310150001005021,3,4
...,...,...,...,...,...,...,...,...,...,...
37259,3,8,210450,001,011,11,1,38210450001011111,4,5
37260,3,8,210450,001,011,12,1,38210450001011121,3,4
37261,3,8,210450,001,011,12,1,38210450001011121,2,4
37262,3,8,210450,001,011,12,1,38210450001011121,4,4
37263,3,8,210450,001,011,12,1,38210450001011121,1,4

In [17]:
# Definimos una función que sume pero devuelva NA si todos son NA
def sum_with_na(series):
    if series.isna().all():
        return pd.NA
    else:
        return series.sum(skipna=True)

In [18]:
print("Ingreso medio de un hogar t4: ", data['ingr_t4_h'].mean())
print("Mediana del ingreso de un hogar t4: ", data['ingr_t4_h'].median())

Ingreso medio de un hogar t4:  6824.376304224683
Mediana del ingreso de un hogar t4:  1969.133783595454

In [19]:
len(data)

ingr_t1_h     459.55958
ingr_t2_h    441.616281
ingr_t3_h    420.997129
ingr_t4_h    387.513547
dtype: object

In [20]:
data['edad'] = data['edad'].apply(lambda x: x if type(x) == int else 0)

Ingreso medio de un hogar t4:  387.51354666344287
Mediana del ingreso de un hogar t4:  298.55547056257564

In [21]:
len(data)

0        70
1        63
2        45
3        28
4        24
         ..
37259    16
37260    40
37261    33
37262     2
37263    50
Name: edad, Length: 37264, dtype: int64

En este caso en la variable edad tenemos números y el texto 'menos de un año' así que primero transformamos todas las filas que digan 'menos de un año' a 0

In [22]:
data['edad'] = data['edad'].apply(lambda x: x if type(x) == int else 0)

In [23]:
data = data.loc[(data['edad'] >= 0) & (data['edad'] < 100)]
len(data)

37264

In [24]:
k = 0.4
s = 0.9

In [25]:
# Si es necesario calcular el número de niños
data['es_nino'] = data['edad'] < 10

data['ninos'] = data.groupby('idef_hogar')['es_nino'].transform('sum')

# Si es necesario calcular el número de adultos
data['es_adulto'] = data['edad'] > 10

data['adultos'] = data.groupby('idef_hogar')['es_adulto'].transform('sum')

In [26]:
data['escala'] = (data['adultos'] + k * data['ninos']) ** s

In [27]:
data['ingr_t_t1'] = data['ingr_t1_h'] / data['escala']
data['ingr_t_t2'] = data['ingr_t2_h'] / data['escala']
data['ingr_t_t3'] = data['ingr_t3_h'] / data['escala']
data['ingr_t_t4'] = data['ingr_t4_h'] / data['escala']

In [28]:
data[['ingr_t_t1', 'ingr_t_t2', 'ingr_t_t3', 'ingr_t_t4']]

        ingr_t_t1   ingr_t_t2   ingr_t_t3   ingr_t_t4
0            <NA>        <NA>        <NA>        <NA>
1            <NA>        <NA>        <NA>        <NA>
2            <NA>        <NA>        <NA>        <NA>
3      120.104454  115.270441  109.944137  101.306198
4      120.104454  115.270441  109.944137  101.306198
...           ...         ...         ...         ...
37259   66.636578   63.954562   60.999412   56.206894
37260        <NA>        <NA>        <NA>        <NA>
37261        <NA>        <NA>        <NA>        <NA>
37262        <NA>        <NA>        <NA>        <NA>
37263        <NA>        <NA>        <NA>        <NA>

[37264 rows x 4 columns]

In [29]:
print("Ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].mean())
print("Mediana del ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].median())

Ingreso individual descontando cargas familiares t4:  102.29658868675642
Mediana del ingreso individual descontando cargas familiares t4:  76.7440904868808

In [30]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))

In [61]:
# Asigna el umbral por trimestre si hay umbral por región modificar
data['umbral'] = data['trimestre'].map(umbral_dict)

data['umbral'] = data.groupby('idef_hogar')['umbral'].transform('mean')

In [31]:
datos_final = pd.DataFrame(index=['t1', 't2', 't3', 't4'], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio'])

In [32]:
data['persona_fexp'] = 1 * data['fexp']

In [33]:
for t in [1, 2, 3, 4]:
    condicion = data['trimestre'] == t
    col_ingr = f'ingr_t_t{t}'
    col_pobres = f'pobres_t{t}'

    # una columna que identifica a quienes están por debajo de la línea de pobreza por trimestre
    data.loc[condicion, col_pobres] = (
        (data.loc[condicion, col_ingr] - data.loc[condicion, 'umbral']) < 0
    ).astype(int)

In [34]:
data[['pobres_t1', 'pobres_t2', 'pobres_t3', 'pobres_t4']].sum()

pobres_t1    7981
pobres_t2    8595
pobres_t3    9012
pobres_t4    9721
dtype: int64

In [35]:
print("pobreza t1: ", (data['pobres_t1'] * data['fexp']).sum()/data.loc[data['trimestre'] == 1]['persona_fexp'].sum())
print("pobreza t2: ", (data['pobres_t2'] * data['fexp']).sum()/data.loc[data['trimestre'] == 2]['persona_fexp'].sum())
print("pobreza t3: ", (data['pobres_t3'] * data['fexp']).sum()/data.loc[data['trimestre'] == 3]['persona_fexp'].sum())
print("pobreza t4: ", (data['pobres_t4'] * data['fexp']).sum()/data.loc[data['trimestre'] == 4]['persona_fexp'].sum())

pobreza t1:  0.32538124093331483
pobreza t2:  0.34766679397528094
pobreza t3:  0.37614973283086417
pobreza t4:  0.40560720925652627

In [36]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data['trimestre'] == t].copy()

    # Calculamos una columna de pobres
    df_temp['pobres'] = (df_temp[f'ingr_t_t{t}'] - umbral_dict[t]) < 0

    # Ratio de pobres sobre el total
    ratio = (umbral_dict[t] - df_temp[f'ingr_t_t{t}']) / umbral_dict[t]

    # Calculamos el índice para alpha 0, 1 y 2 solo donde 'pobres' == True.
    for i in range(3):
        col = f'fgt{i}'
        df_temp[col] = np.where(df_temp['pobres'], ratio**i, 0)

    # Cálculo del índice ponderado: se usa el factor de expansión como peso
    peso_total = df_temp['fexp'].sum()
    fgt0 = (df_temp['fgt0'] * df_temp['fexp']).sum() / peso_total
    fgt1 = (df_temp['fgt1'] * df_temp['fexp']).sum() / peso_total
    fgt2 = (df_temp['fgt2'] * df_temp['fexp']).sum() / peso_total
    
    # Guardamos los resultados
    datos_final.loc[f't{t}', 'fgt0'] = fgt0
    datos_final.loc[f't{t}', 'fgt1'] = fgt1
    datos_final.loc[f't{t}', 'fgt2'] = fgt2

In [37]:
datos_final

        fgt0      fgt1      fgt2  a25  a50  a75 ingreso_promedio
t1  0.325381  0.131106  0.072778  NaN  NaN  NaN              NaN
t2  0.347667  0.139979  0.078101  NaN  NaN  NaN              NaN
t3   0.37615  0.150229  0.083342  NaN  NaN  NaN              NaN
t4  0.405607  0.169078  0.094952  NaN  NaN  NaN              NaN

In [38]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data['trimestre'] == t].copy()

    # Suma total de los factores de expansión para el trimestre
    peso_total = df_temp['fexp'].sum()
    
    # Ingreso promedio ponderado
    mu = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total

    # Calculamos el índice A para epsilon 0.25, 0.5 y 0.75 utilizando los pesos
    indices = {}
    for i in [0.25, 0.5, 0.75]:
        A_i = ((df_temp[f'ingr_t_t{t}']**(1-i) * df_temp['fexp']).sum() / peso_total)**(1/(1-i))
        indices[i] = A_i

    # Ratio de pobreza con el índice total (aplicando la fórmula)
    a25 = 1 - 1/mu * indices[0.25]
    a50 = 1 - 1/mu * indices[0.5]
    a75 = 1 - 1/mu * indices[0.75]

    # Guardamos los resultados
    datos_final.loc[f't{t}', 'a25'] = a25
    datos_final.loc[f't{t}', 'a50'] = a50
    datos_final.loc[f't{t}', 'a75'] = a75

In [39]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.325381,0.131106,0.072778,0.084123,0.160792,0.231406,NaN
t2,0.347667,0.139979,0.078101,0.084089,0.160819,0.231576,NaN
t3,0.37615,0.150229,0.083342,0.084051,0.160552,0.2309,NaN
t4,0.405607,0.169078,0.094952,0.08414,0.160698,0.231069,NaN

In [40]:
for t in [1, 2, 3, 4]:
    df_temp = data.loc[data['trimestre'] == t].copy()
    
    # Calcula la suma total de los factores de expansión
    peso_total = df_temp['fexp'].sum()
    
    # Calcula el ingreso promedio ponderado
    media_ponderada = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total
    
    datos_final.loc[f't{t}', 'ingreso_promedio'] = media_ponderada

In [41]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.325381,0.131106,0.072778,0.084123,0.160792,0.231406,127.740381
t2,0.347667,0.139979,0.078101,0.084089,0.160819,0.231576,122.505356
t3,0.37615,0.150229,0.083342,0.084051,0.160552,0.2309,116.647702
t4,0.405607,0.169078,0.094952,0.08414,0.160698,0.231069,107.560388

### Inserta los cálculos en la base final

In [42]:
indices = pd.read_csv("indices.csv", encoding='latin-1')

In [43]:
ano = 1996
# Asegurar que el índice de datos_final coincide con trimestres 1..4
datos_final = datos_final.copy()
datos_final["trimestre"] = [1, 2, 3, 4]
datos_final["Año"] = ano

# Reemplazar en indices usando mask
for col in ["fgt0","fgt1","fgt2","a25","a50","a75","ingreso_promedio"]:
    indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

/tmp/ipykernel_96289/2593569122.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.32538124093331483 0.34766679397528094 0.37614973283086417
 0.40560720925652627]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96289/2593569122.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.1311064574283386 0.13997923261000872 0.15022873552236893
 0.16907799652732647]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96289/2593569122.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.07277834087483598 0.07810126890178032 0.08334155393346342
 0.09495215816359397]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96289/2593569122.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.08412302272335392 0.08408936044487259 0.08405133118430586
 0.08414034652927105]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96289/2593569122.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.16079164048266237 0.16081944694748096 0.16055214156142317
 0.16069814990767917]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96289/2593569122.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.2314060686652738 0.2315764120229905 0.23089976227031472
 0.23106872052280691]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values
/tmp/ipykernel_96289/2593569122.py:9: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[127.74038108244262 122.50535569195739 116.64770234072608 107.560387917482]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  indices.loc[indices["Año"].eq(ano), col] = datos_final[col].values

In [44]:
datos_final.to_csv('datos_final1996.csv')