In [1]:
import numpy as np
import pandas as pd

In [2]:
# data = pd.read_stata(r"Z:\harmonized\ECU\ENEMDU\data_arm\ECU_1990m11_BID.dta") # para bases de stata
data = pd.read_stata(r"Bases Enendum 96, 97, 98\ECU_1997m11.dta") # para bases de stata

In [3]:
data.columns

Index(['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar',
       'formul', 'persona', 'numpers', 'resumen', 'reljefe', 'edad', 'sexo',
       'nivinst', 'anoinst', 'asistea', 'sabele', 'iess', 'donnac', 'lugnac',
       'siemvic', 'donvian', 'lugvian', 'cuanvic', 'trabajo', 'actayuda',
       'hortrasa', 'ratmeh', 'hormas', 'ratmah', 'aunotra', 'pornot',
       'bustrasa', 'bustrama', 'sitios', 'amigos', 'directo', 'prensa',
       'agepu', 'agepri', 'tresne', 'tiembus', 'motnobus', 'deseatra',
       'condina', 'trabant', 'motnotra', 'tiemnot', 'rama', 'grupo',
       'catetrab', 'pertrabn', 'npertra', 'numtrab', 'estabil', 'hortrahp',
       'hortrahs', 'hortraho', 'ramas', 'grupos', 'cates', 'ingpat', 'ingasg',
       'ingepv', 'ingdom', 'ingjub', 'ingalq', 'ingotr', 'nov', 'dic', 'ene',
       'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct',
       'condact', 'peamsiu', 'secins', 'subequ', 'ingrl', 'fexp1', 'fexp'],
      dtype='object')

- rn - regiÓn natural
- dominio - dominio
- ciudad - ciudad
- zona - zona
- sector - sector
- vivienda - vivienda
- hogar - hogar
- formul - formulario
- persona - persona
- numpers - nÚmero de personas
- edad - edad
- sexo - sexo
- iess - es afiliado al iess
- trabajo - trabajó la semana pasada
- rama - rama de actividad
- grupo - grupo de ocupación
- catetrab - categoría de ocupación
- ramas - rama de actividad secundaria
- grupos - grupo de ocupación secundario
- cates - categoría de ocupación secundaria
- ingpat - ingresos como patrono o cuenta propia
- ingasg - ingresos como asalariado de gobierno
- ingepv - ingreso asalariado empresa privada
- ingdom - ingreso como empleada doméstica
- ingjub - ingresos por jubilación o pensión
- ingalq - ingreso por alquileres, rentas o intereses
- ingotr - por otros ingresos
- ingrl - ingresos
- fexp1 - factor de expanción 1
- fexp - factor de expanción

In [4]:
data = data[['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar',
       'formul', 'persona', 'numpers', 'edad', 'trabajo', 'ingpat', 'ingasg',
       'ingepv', 'ingdom', 'ingjub', 'ingalq', 'ingotr', 'nov', 'dic', 'ene',
       'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'ingrl', 'fexp1', 'fexp']]

In [5]:
data ['sum_ing'] = data [['ingasg', 'ingepv', 'ingdom']].sum(axis=1)

In [6]:
data['suma_ing_ene'] = data.apply(lambda x: x['sum_ing'] if x['ene'] == 'trabajando' else None, axis=1)
data['suma_ing_feb'] = data.apply(lambda x: x['sum_ing'] if x['feb'] == 'trabajando' else None, axis=1)
data['suma_ing_mar'] = data.apply(lambda x: x['sum_ing'] if x['mar'] == 'trabajando' else None, axis=1)
data['suma_ing_abr'] = data.apply(lambda x: x['sum_ing'] if x['abr'] == 'trabajando' else None, axis=1)
data['suma_ing_may'] = data.apply(lambda x: x['sum_ing'] if x['may'] == 'trabajando' else None, axis=1)
data['suma_ing_jun'] = data.apply(lambda x: x['sum_ing'] if x['jun'] == 'trabajando' else None, axis=1)
data['suma_ing_jul'] = data.apply(lambda x: x['sum_ing'] if x['jul'] == 'trabajando' else None, axis=1)
data['suma_ing_ago'] = data.apply(lambda x: x['sum_ing'] if x['ago'] == 'trabajando' else None, axis=1)
data['suma_ing_sep'] = data.apply(lambda x: x['sum_ing'] if x['sep'] == 'trabajando' else None, axis=1)
data['suma_ing_oct'] = data.apply(lambda x: x['sum_ing'] if x['oct'] == 'trabajando' else None, axis=1)
data['suma_ing_nov'] = data.apply(lambda x: x['sum_ing'] if x['nov'] == 'trabajando' else None, axis=1)
data['suma_ing_dic'] = data.apply(lambda x: x['sum_ing'] if x['dic'] == 'trabajando' else None, axis=1)

In [7]:
data['suma_ing_t1'] = (data['suma_ing_ene'] + data['suma_ing_feb'] + data['suma_ing_mar'])/3
data['suma_ing_t2'] = (data['suma_ing_abr'] + data['suma_ing_may'] + data['suma_ing_jun'])/3
data['suma_ing_t3'] = (data['suma_ing_jul'] + data['suma_ing_ago'] + data['suma_ing_sep'])/3
data['suma_ing_t4'] = (data['suma_ing_oct'] + data['suma_ing_nov'] + data['suma_ing_dic'])/3

In [8]:
# Llenar valores perdidos con un dato (0)
data['suma_ing_t1'] = data['suma_ing_t1'].fillna(0)
data['suma_ing_t2'] = data['suma_ing_t2'].fillna(0)
data['suma_ing_t3'] = data['suma_ing_t3'].fillna(0)
data['suma_ing_t4'] = data['suma_ing_t4'].fillna(0)

In [9]:
data

,rn,dominio,ciudad,zona,sector,vivienda,hogar,formul,persona,numpers,...,suma_ing_jul,suma_ing_ago,suma_ing_sep,suma_ing_oct,suma_ing_nov,suma_ing_dic,suma_ing_t1,suma_ing_t2,suma_ing_t3,suma_ing_t4
0,1,6,100450,004,008,01,1,1,1,3,...,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0,9999999.0
1,1,6,100450,004,008,01,1,1,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,1,6,100450,004,008,01,1,1,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,1,6,100450,004,008,02,1,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,1,6,100450,004,008,02,1,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36679,2,2,090150,179,008,12,1,1,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
36680,2,2,090150,179,008,12,1,1,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
36681,2,7,090750,013,004,01,1,1,4,4,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
36682,2,6,091550,004,004,11,1,1,7,10,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
36683,1,1,170150,053,008,07,1,1,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0

In [10]:
data['suma_ing_t1'].mean()

np.float64(281251.6249591102)

In [11]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\jairo\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\jairo\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import openpyxl
print(openpyxl.__version__)

3.1.5

In [16]:
import pandas as pd

data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos', engine='openpyxl')

In [18]:
# Carga base de datos con ipc
data_externa = pd.read_excel("data_externa.xlsx", sheet_name='datos')

# filtra año de interés
datos_actual = data_externa[data_externa['Año'] == 1997]
datos_base = data_externa[data_externa['Año'] == 2014]

In [19]:
datos_actual

,Año,trimestre,Nacional,Sierra,Costa,Guayaquil,Esmeraldas,Machala,Manta,Santo Domingo,Quito,Loja,Cuenca,Ambato,salario básico unificado,tipo de cambio,umbral de pobreza
28,1997,1,9.57592,NaN,NaN,11.043915,NaN,NaN,NaN,NaN,9.896307,NaN,8.005899,NaN,23.757127,3756.000000,493.696921
29,1997,2,9.57592,NaN,NaN,11.043915,NaN,NaN,NaN,NaN,9.896307,NaN,8.005899,NaN,25.007502,3924.000000,497.666602
30,1997,3,9.57592,NaN,NaN,11.043915,NaN,NaN,NaN,NaN,9.896307,NaN,8.005899,NaN,25.007502,4098.333333,501.673280
31,1997,4,9.57592,NaN,NaN,11.043915,NaN,NaN,NaN,NaN,9.896307,NaN,8.005899,NaN,25.007502,4340.333333,505.894834

In [20]:
ipc_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Guayaquil': fila['Guayaquil'],
        'Quito': fila['Quito'],
        'Cuenca': fila['Cuenca']
    }
     for _, fila in datos_actual.iterrows()
     }

ipc_base_dict = {fila['trimestre']: {
        'Nacional': fila['Nacional'],
        'Guayaquil': fila['Guayaquil'],
        'Quito': fila['Quito'],
        'Cuenca': fila['Cuenca']
    }
     for _, fila in datos_base.iterrows()
     }

tipo_cambio_dict = dict(zip(datos_actual['trimestre'], datos_actual['tipo de cambio']))

In [21]:
tipo_cambio_dict

{1: 3756.0, 2: 3924.0, 3: 4098.33333333333, 4: 4340.33333333333}

In [22]:
# Corregimos los códigos para usarlos cómo texto
data['ciudad'] = data['ciudad'].apply(str)
data['ciudad'] = data['ciudad'].apply(lambda x: '0' + x if len(x) == 5 else x)

data['ciudad_2'] = data['ciudad'].apply(lambda x: x[:2])

In [23]:
parroquia_dict = {
    '01': 'Cuenca',
    '09': 'Guayaquil',
    '17': 'Quito'
}

data['ciudad_asignada'] = data['ciudad_2'].apply(lambda x: parroquia_dict.get(x, 'Nacional'))

In [24]:
data['ciudad_asignada']

0         Nacional
1         Nacional
2         Nacional
3         Nacional
4         Nacional
           ...
36679    Guayaquil
36680    Guayaquil
36681    Guayaquil
36682    Guayaquil
36683        Quito
Name: ciudad_asignada, Length: 36684, dtype: object

In [25]:
def assgna_trimestre(fila):
    if 'trabajando' in [fila['ene'], fila['feb'], fila['mar']]:
        return 1
    elif 'trabajando' in [fila['abr'], fila['may'], fila['jun']]:
        return 2
    elif 'trabajando' in [fila['jul'], fila['ago'], fila['sep']]:
        return 3
    elif 'trabajando' in [fila['oct'], fila['nov'], fila['dic']]:
        return 4
    else:
        return None
    
data['trimestre'] = data.apply(assgna_trimestre, axis=1)

In [26]:
data['trimestre']

0        1.0
1        NaN
2        NaN
3        NaN
4        NaN
        ...
36679    NaN
36680    NaN
36681    NaN
36682    NaN
36683    NaN
Name: trimestre, Length: 36684, dtype: float64

In [27]:
# Función que asigna valores correspondientes
def asigna_ipc(fila):
    return ipc_dict.get(fila['trimestre'], {}).get(fila['ciudad_asignada'], None)

def asigna_ipc_base(fila):
    return ipc_base_dict.get(fila['trimestre'], {}).get(fila['ciudad_asignada'], None)

In [28]:
data['ipc'] = data.apply(asigna_ipc, axis=1)
data['ipc_base'] = data.apply(asigna_ipc_base, axis=1)
data['tipo_cambio'] = data['trimestre'].map(tipo_cambio_dict)

In [29]:
data['ipc']

0        9.57592
1            NaN
2            NaN
3            NaN
4            NaN
          ...
36679        NaN
36680        NaN
36681        NaN
36682        NaN
36683        NaN
Name: ipc, Length: 36684, dtype: float64

In [30]:
data['ipc_base']

0        98.083034
1              NaN
2              NaN
3              NaN
4              NaN
           ...
36679          NaN
36680          NaN
36681          NaN
36682          NaN
36683          NaN
Name: ipc_base, Length: 36684, dtype: float64

In [31]:
data['tipo_cambio']

0        3756.0
1           NaN
2           NaN
3           NaN
4           NaN
          ...
36679       NaN
36680       NaN
36681       NaN
36682       NaN
36683       NaN
Name: tipo_cambio, Length: 36684, dtype: float64

In [32]:
# Calculamos el deflactor
data['def'] = (data['ipc_base'] / data['ipc'])

In [33]:
data['def']

0        10.242675
1              NaN
2              NaN
3              NaN
4              NaN
           ...
36679          NaN
36680          NaN
36681          NaN
36682          NaN
36683          NaN
Name: def, Length: 36684, dtype: float64

In [34]:
data['ingr_t1_r'] = (data['suma_ing_t1'] / data['tipo_cambio']) * data['def']
data['ingr_t2_r'] = (data['suma_ing_t2'] / data['tipo_cambio']) * data['def']
data['ingr_t3_r'] = (data['suma_ing_t3'] / data['tipo_cambio']) * data['def']
data['ingr_t4_r'] = (data['suma_ing_t4'] / data['tipo_cambio']) * data['def']

In [35]:
data[['suma_ing_t1', 'suma_ing_t2', 'suma_ing_t3', 'suma_ing_t4', 'ipc', 'ipc_base', 'def', 'tipo_cambio', 'ingr_t1_r', 'ingr_t2_r', 'ingr_t3_r', 'ingr_t4_r']]

,suma_ing_t1,suma_ing_t2,suma_ing_t3,suma_ing_t4,ipc,ipc_base,def,tipo_cambio,ingr_t1_r,ingr_t2_r,ingr_t3_r,ingr_t4_r
0,9999999.0,9999999.0,9999999.0,9999999.0,9.57592,98.083034,10.242675,3756.0,27270.164227,27270.164227,27270.164227,27270.164227
1,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
36679,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36680,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36681,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36682,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36683,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
data['ingr_t4_r'].mean()

np.float64(1755.3027141983766)

In [37]:
columnas_idef = ['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar']

data['idef_hogar'] = data[columnas_idef].astype(str).agg(''.join, axis=1)
len(data['idef_hogar'].unique())

8259

In [38]:
data [['rn', 'dominio', 'ciudad', 'zona', 'sector', 'vivienda', 'hogar', 'idef_hogar', 'persona', 'numpers']]

,rn,dominio,ciudad,zona,sector,vivienda,hogar,idef_hogar,persona,numpers
0,1,6,100450,004,008,01,1,16100450004008011,1,3
1,1,6,100450,004,008,01,1,16100450004008011,2,3
2,1,6,100450,004,008,01,1,16100450004008011,3,3
3,1,6,100450,004,008,02,1,16100450004008021,1,2
4,1,6,100450,004,008,02,1,16100450004008021,2,2
...,...,...,...,...,...,...,...,...,...,...
36679,2,2,090150,179,008,12,1,22090150179008121,3,4
36680,2,2,090150,179,008,12,1,22090150179008121,4,4
36681,2,7,090750,013,004,01,1,27090750013004011,4,4
36682,2,6,091550,004,004,11,1,26091550004004111,7,10
36683,1,1,170150,053,008,07,1,11170150053008071,3,3

In [39]:
data['ingr_t1_h'] = data.groupby('idef_hogar')['ingr_t1_r'].transform('sum')
data['ingr_t2_h'] = data.groupby('idef_hogar')['ingr_t2_r'].transform('sum')
data['ingr_t3_h'] = data.groupby('idef_hogar')['ingr_t3_r'].transform('sum')
data['ingr_t4_h'] = data.groupby('idef_hogar')['ingr_t4_r'].transform('sum')

In [40]:
data[['ingr_t1_h', 'ingr_t2_h', 'ingr_t3_h', 'ingr_t4_h']]

          ingr_t1_h     ingr_t2_h     ingr_t3_h     ingr_t4_h
0      27270.164227  27270.164227  27270.164227  27270.164227
1      27270.164227  27270.164227  27270.164227  27270.164227
2      27270.164227  27270.164227  27270.164227  27270.164227
3          0.000000      0.000000      0.000000      0.000000
4          0.000000      0.000000      0.000000      0.000000
...             ...           ...           ...           ...
36679      0.000000      0.000000      0.000000      0.000000
36680      0.000000      0.000000      0.000000      0.000000
36681   3076.193196   3076.193196   3076.193196   3076.193196
36682    946.520983    946.520983    946.520983    946.520983
36683      0.000000      0.000000      0.000000      0.000000

[36684 rows x 4 columns]

In [41]:
print("Ingreso medio de un hogar t4: ", data['ingr_t4_h'].mean())
print("Mediana del ingreso de un hogar t4: ", data['ingr_t4_h'].median())

Ingreso medio de un hogar t4:  3755.2504755773584
Mediana del ingreso de un hogar t4:  1636.2100172676492

In [42]:
len(data)

36684

In [43]:
data['edad'] = data['edad'].apply(lambda x: x if type(x) == int else 0)

In [44]:
data ['edad']

0        34
1        38
2         6
3        67
4        66
         ..
36679    14
36680     8
36681    15
36682    10
36683    67
Name: edad, Length: 36684, dtype: int64

In [46]:
data = data.loc[(data['edad'] >= 0) & (data['edad'] < 100)]
len(data)

36684

In [47]:
k = 0.4
s = 0.9

In [48]:
# Si es necesario calcular el número de niños
data['es_nino'] = data['edad'] < 10

data['ninos'] = data.groupby('idef_hogar')['es_nino'].transform('sum')

# Si es necesario calcular el número de adultos
data['es_adulto'] = data['edad'] > 10

data['adultos'] = data.groupby('idef_hogar')['es_adulto'].transform('sum')

In [49]:
data['escala'] = (data['adultos'] + k * data['ninos']) ** s

In [50]:
data['ingr_t_t1'] = data['ingr_t1_h'] / data['escala']
data['ingr_t_t2'] = data['ingr_t2_h'] / data['escala']
data['ingr_t_t3'] = data['ingr_t3_h'] / data['escala']
data['ingr_t_t4'] = data['ingr_t4_h'] / data['escala']

In [51]:
data[['ingr_t_t1', 'ingr_t_t2', 'ingr_t_t3', 'ingr_t_t4']]

          ingr_t_t1     ingr_t_t2     ingr_t_t3     ingr_t_t4
0      12402.168737  12402.168737  12402.168737  12402.168737
1      12402.168737  12402.168737  12402.168737  12402.168737
2      12402.168737  12402.168737  12402.168737  12402.168737
3          0.000000      0.000000      0.000000      0.000000
4          0.000000      0.000000      0.000000      0.000000
...             ...           ...           ...           ...
36679      0.000000      0.000000      0.000000      0.000000
36680      0.000000      0.000000      0.000000      0.000000
36681    883.404516    883.404516    883.404516    883.404516
36682    160.151496    160.151496    160.151496    160.151496
36683      0.000000      0.000000      0.000000      0.000000

[36684 rows x 4 columns]

In [52]:
print("Ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].mean())
print("Mediana del ingreso individual descontando cargas familiares t4: ", data['ingr_t_t4'].median())

Ingreso individual descontando cargas familiares t4:  987.7890712278229
Mediana del ingreso individual descontando cargas familiares t4:  407.72516117696057

In [53]:
umbral_dict = dict(zip(datos_actual['trimestre'], datos_actual['umbral de pobreza']))

In [54]:
# Asigna el umbral por trimestre si hay umbral por región modificar
data['umbral'] = data['trimestre'].map(umbral_dict)

data['umbral'] = data.groupby('idef_hogar')['umbral'].transform('mean')

In [55]:
datos_final = pd.DataFrame(index=['t1', 't2', 't3', 't4'], columns=['fgt0', 'fgt1', 'fgt2', 'a25', 'a50', 'a75', 'ingreso_promedio'])

In [56]:
data['persona_fexp'] = 1 * data['fexp']

In [57]:
for t in [1, 2, 3, 4]:
    condicion = data['trimestre'] == t
    col_ingr = f'ingr_t_t{t}'
    col_pobres = f'pobres_t{t}'

    # una columna que identifica a quienes están por debajo de la línea de pobreza por trimestre
    data.loc[condicion, col_pobres] = (
        (data.loc[condicion, col_ingr] - data.loc[condicion, 'umbral']) < 0
    ).astype(int)

In [58]:
print("pobreza t1: ", (data['pobres_t1'] * data['fexp']).sum()/data.loc[data['trimestre'] == 1]['persona_fexp'].sum())
print("pobreza t2: ", (data['pobres_t2'] * data['fexp']).sum()/data.loc[data['trimestre'] == 2]['persona_fexp'].sum())
print("pobreza t3: ", (data['pobres_t3'] * data['fexp']).sum()/data.loc[data['trimestre'] == 3]['persona_fexp'].sum())
print("pobreza t4: ", (data['pobres_t4'] * data['fexp']).sum()/data.loc[data['trimestre'] == 4]['persona_fexp'].sum())

pobreza t1:  0.46462435886816844
pobreza t2:  0.5600501987032002
pobreza t3:  0.5609350728353085
pobreza t4:  0.8168677577350376

In [59]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data['trimestre'] == t].copy()

    # Calculamos una columna de pobres
    df_temp['pobres'] = (df_temp[f'ingr_t_t{t}'] - umbral_dict[t]) < 0

    # Ratio de pobres sobre el total
    ratio = (umbral_dict[t] - df_temp[f'ingr_t_t{t}']) / umbral_dict[t]

    # Calculamos el índice para alpha 0, 1 y 2 solo donde 'pobres' == True.
    for i in range(3):
        col = f'fgt{i}'
        df_temp[col] = np.where(df_temp['pobres'], ratio**i, 0)

    # Cálculo del índice ponderado: se usa el factor de expansión como peso
    peso_total = df_temp['fexp'].sum()
    fgt0 = (df_temp['fgt0'] * df_temp['fexp']).sum() / peso_total
    fgt1 = (df_temp['fgt1'] * df_temp['fexp']).sum() / peso_total
    fgt2 = (df_temp['fgt2'] * df_temp['fexp']).sum() / peso_total
    
    # Guardamos los resultados
    datos_final.loc[f't{t}', 'fgt0'] = fgt0
    datos_final.loc[f't{t}', 'fgt1'] = fgt1
    datos_final.loc[f't{t}', 'fgt2'] = fgt2

In [60]:
for t in [1, 2, 3, 4]:
    # Filtramos para cada trimestre
    df_temp = data.loc[data['trimestre'] == t].copy()

    # Suma total de los factores de expansión para el trimestre
    peso_total = df_temp['fexp'].sum()
    
    # Ingreso promedio ponderado
    mu = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total

    # Calculamos el índice A para epsilon 0.25, 0.5 y 0.75 utilizando los pesos
    indices = {}
    for i in [0.25, 0.5, 0.75]:
        A_i = ((df_temp[f'ingr_t_t{t}']**(1-i) * df_temp['fexp']).sum() / peso_total)**(1/(1-i))
        indices[i] = A_i

    # Ratio de pobreza con el índice total (aplicando la fórmula)
    a25 = 1 - 1/mu * indices[0.25]
    a50 = 1 - 1/mu * indices[0.5]
    a75 = 1 - 1/mu * indices[0.75]

    # Guardamos los resultados
    datos_final.loc[f't{t}', 'a25'] = a25
    datos_final.loc[f't{t}', 'a50'] = a50
    datos_final.loc[f't{t}', 'a75'] = a75

In [61]:
for t in [1, 2, 3, 4]:
    df_temp = data.loc[data['trimestre'] == t].copy()
    
    # Calcula la suma total de los factores de expansión
    peso_total = df_temp['fexp'].sum()
    
    # Calcula el ingreso promedio ponderado
    media_ponderada = (df_temp[f'ingr_t_t{t}'] * df_temp['fexp']).sum() / peso_total
    
    datos_final.loc[f't{t}', 'ingreso_promedio'] = media_ponderada

In [62]:
datos_final

,fgt0,fgt1,fgt2,a25,a50,a75,ingreso_promedio
t1,0.464344,0.331825,0.293666,0.247222,0.482865,0.754749,1364.786894
t2,0.561734,0.406307,0.36263,0.244159,0.490074,0.785483,836.11581
t3,0.572276,0.399513,0.346007,0.261565,0.512997,0.790279,1222.874494
t4,0.816868,0.589565,0.523544,0.37695,0.669523,0.908227,733.014509

In [63]:
datos_final.to_csv('datos_final1997.csv')